name: pr
on:
  pull_request: {}
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm check:format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm check:lint
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm check:types
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
        environment: [happy-dom, node]
    name: Node ${{ matrix.node }} @env ${{matrix.environment}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm build
      - run: pnpm test -- --environment ${{ matrix.environment }}
